//
//  RedGateView.swift
//  ProgressBar
//
//  Created by Carrtoonist on 11/1/16.
//  Copyright © 2016 NextPlanetStudio. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class RedGateDraw : NSObject {

    //// Drawing Methods

    public dynamic class func drawRedGate(frame: CGRect = CGRect(x: 0, y: 0, width: 144, height: 72), leftGateAngle: CGFloat = 0, rightGateAngle: CGFloat = 0) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!

        //// Color Declarations
        let color = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Gate Left Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 6.15, y: frame.minY + 65.83)
        context.rotate(by: -leftGateAngle * CGFloat.pi/180)

        let gateLeftPath = UIBezierPath(roundedRect: CGRect(x: -6.15, y: -5.83, width: 72, height: 12), byRoundingCorners: [.topRight, .bottomLeft, .bottomRight], cornerRadii: CGSize(width: 6, height: 6))
        gateLeftPath.close()
        color.setFill()
        gateLeftPath.fill()

        context.restoreGState()


        //// Gate Right Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 138.01, y: frame.minY + 66.01)
        context.rotate(by: -rightGateAngle * CGFloat.pi/180)

        let gateRightPath = UIBezierPath(roundedRect: CGRect(x: -66.01, y: -6.01, width: 72, height: 12), byRoundingCorners: [.topLeft, .bottomLeft, .bottomRight], cornerRadii: CGSize(width: 6, height: 6))
        gateRightPath.close()
        color.setFill()
        gateRightPath.fill()

        context.restoreGState()
    }

}
