//
//  SpinningCirclesDraw.swift
//  ProgressBar
//
//  Created by Carrtoonist on 11/1/16.
//  Copyright © 2016 NextPlanetStudio. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class SpinningCirclesDraw : NSObject {

    //// Drawing Methods

    public dynamic class func drawSpinningCircles(frame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 300), yellowAngle: CGFloat = 0, blueAngle: CGFloat = 0, greenAngle: CGFloat = 0, redAngle: CGFloat = 0) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!

        //// Color Declarations
        let color = UIColor(red: 0.000, green: 0.840, blue: 0.290, alpha: 0.353)
        let color2 = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 0.355)
        let color3 = UIColor(red: 0.000, green: 0.000, blue: 1.000, alpha: 0.353)
        let color4 = UIColor(red: 0.887, green: 1.000, blue: 0.000, alpha: 0.351)

        //// Red Oval Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 112.5, y: frame.minY + 150)
        context.rotate(by: -redAngle * CGFloat.pi/180)

        let redOvalPath = UIBezierPath(ovalIn: CGRect(x: -37.5, y: -75, width: 150, height: 150))
        color2.setFill()
        redOvalPath.fill()

        context.restoreGState()


        //// Green Oval Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 150, y: frame.minY + 112.5)
        context.rotate(by: -greenAngle * CGFloat.pi/180)

        let greenOvalPath = UIBezierPath(ovalIn: CGRect(x: -75, y: -37.5, width: 150, height: 150))
        color.setFill()
        greenOvalPath.fill()

        context.restoreGState()


        //// Blue Oval Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 150, y: frame.minY + 187.5)
        context.rotate(by: -blueAngle * CGFloat.pi/180)

        let blueOvalPath = UIBezierPath(ovalIn: CGRect(x: -75, y: -112.5, width: 150, height: 150))
        color3.setFill()
        blueOvalPath.fill()

        context.restoreGState()


        //// Yellow Oval Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 187.5, y: frame.minY + 150)
        context.rotate(by: -yellowAngle * CGFloat.pi/180)

        let yellowOvalPath = UIBezierPath(ovalIn: CGRect(x: -112.5, y: -75, width: 150, height: 150))
        color4.setFill()
        yellowOvalPath.fill()

        context.restoreGState()
    }

}
